DISCOUNT = {
    "YOURFAVE" : 10,
    "COMEBACK" : 5,
    "THANKYOUDEAR" : 10,
}

TAUX = {
    'Germany': ['Allemagne', 19, 7],
    'Austria': ['Autriche', 20, 10],
    'Belgium': ['Belgique', 21, 6],
    'Bulgaria': ['Bulgarie', 20, 9],
    'Cyprus': ['Chypre', 19, 5],
    'Croatia': ['Croatie', 25, 5],
    'Denmark': ['Danemark', 25, None],
    'Spain': ['Espagne', 21, 10],
    'Estonia': ['Estonie', 22, 9],
    'Finland': ['Finlande', 24, 10],
    'France': ['France', 20, 5.5],
    'Greece': ['Grece', 24, 6],
    'Hungary': ['Hongrie', 27, 5],
    'Ireland': ['Irlande', 23, 9],
    'Northern ireland': ['Irlande du nord', 20, 5],
    'Italy': ['Italie', 22, 10],
    'Latvia': ['Lettonie', 21, 12],
    'Lithuania': ['Lituanie', 21, 5],
    'Luxembourg': ['Luxembourg', 17, 8],
    'Malta': ['Malte', 18, 5],
    'Norway': ['Norvege', 25, 15],
    'Netherlands': ['Pays bas', 21, 9],
    'Poland': ['Pologne', 23, 5],
    'Portugal': ['Portugal', 23, 6],
    'Czech republic': ['Rep tcheque', 21, 12],
    'Romania': ['Roumanie', 20, 5],
    'Slovakia': ['Slovaquie', 20, 10],
    'Slovenia': ['Slovenie', 22, 9.5],
    'Sweden': ['Suede', 25, 6]
}